insert into teacher_locations (teacher_id, location_id) values (1, 1);
insert into teacher_locations (teacher_id, location_id) values (1, 2);
insert into teacher_locations (teacher_id, location_id) values (1, 3);
insert into teacher_locations (teacher_id, location_id) values (2, 1);
insert into teacher_locations (teacher_id, location_id) values (3, 2);
insert into teacher_locations (teacher_id, location_id) values (3, 3);
insert into teacher_locations (teacher_id, location_id) values (3, 1);
insert into teacher_locations (teacher_id, location_id) values (2, 1);
insert into teacher_locations (teacher_id, location_id) values (3, 2);
