DROP TABLE IF EXISTS teachers CASCADE;

CREATE TABLE teachers (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  level SMALLINT NOT NULL,
  direct_deposit VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL
);
