DROP TABLE IF EXISTS classes CASCADE;

CREATE TABLE classes (
  id SERIAL PRIMARY KEY NOT NULL,
  teacher_id INTEGER REFERENCES teachers(id) ON DELETE CASCADE,
  location_id INTEGER REFERENCES locations(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  duration(min) TINYINT NOT NULL
);
